version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - "${DB_PORT}:5432"
    networks:
      - mynetwork

  app:
    build: ./
    container_name: 'java_application'
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}'
      - 'SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}'
      - 'SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}'
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge