version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_NAME}'
    ports:
      - "${DB_PORT}:5432"

  app:
    build: ./
    container_name: 'java_application'
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}'
      - 'SPRING_DATASOURCE_USERNAME=${DB_USERNAME}'
      - 'SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}'
    ports:
      - "8080:8080"
    restart: on-failure